title: "Kubernetes Developer Workshop"
description: "Technical hands-on workshop for Kubernetes"
remote_theme: benc-uk/theme-msdark
hide_github: true
hide_tagline: true
favicon: https://kubernetes.io/images/favicon.png
buttons:
  - b0:
    text: Workshop Index
    href: https://code.benco.io/kube-workshop
